#cloud-config
hostname: apache2
users:
  - name: debian
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    shell: /bin/bash
    ssh-authorized-keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFOpayN0rnITq/vWnTdjLyRL9LJnIZBMCKomncGILq5e usuario@da3m0n
chpasswd:
  expire: False
  users:
    - name: debian
      password: debian
      type: text


